name: Deployment
on:
  push:
    branches:
      - master
jobs:
  run-workflow:
    runs-on: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
          
      - name: Download model from registry
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GIT_COMMIT: ${{ github.event.after }}
          MODEL_ARCHIVE_OUTPUT_PATH: "review_classifier.tar.gz"
          MODEL_AWS_BUCKET: "ml-production-artifacts"
          MODEL_AWS_REGION: "eu-central-1"
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
        run: |
          echo $GIT_COMMIT
          python src/download_and_deploy_model.py
          ls
