name: Deployment
on:
  push:
    branches:
      - master
jobs:
  run-workflow:
    runs-on: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
          
      - name: Download model from registry
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          MODEL_ARCHIVE_OUTPUT_PATH: "review_classifier.tar.gz"
          GIT_COMMIT: ${{ github.event.after }}
        run: |
          python src/download_from_registry.py
          ls