name: Quick Training
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]
    paths:
      - 'src'

jobs:
  train:
    runs-on: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
          
      - name: Run training
        env:
          MODEL_EXPORT_DIRECTORY: "review_classifier/1"
          MODEL_ARCHIVE_OUTPUT_PATH: "review_classifier.tar.gz"
        run: |
          python src/train.py

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Register model
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          MODEL_ARCHIVE_OUTPUT_PATH: "review_classifier.tar.gz"
          PULL_REQUEST_ID: ${{ github.event.number }}
        run: |
          echo $PULL_REQUEST_ID
          python src/register.py
