name: Quick Training
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]
jobs:
  run-workflow:
    runs-on: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt
          
      - name: Run training
        env:
          # MODEL_AWS_BUCKET: ml-production-artifacts
          # MODEL_AWS_REGION: eu-central-1
          MODEL_EXPORT_DIRECTORY: "bin/review_classifier/"
          MODEL_ARCHIVE_OUTPUT_PATH: "review_classifier.tar.gz"
        run: |
          python src/train.py

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Register model
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          MODEL_ARCHIVE_OUTPUT_PATH: "review_classifier.tar.gz"
          GIT_COMMIT: ${{ github.event.pull_request.head.sha }}
        run: |
          python src/register.py

      - name: Download model from registry
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          MODEL_ARCHIVE_OUTPUT_PATH: "review_classifier.tar.gz"
          GIT_COMMIT: ${{ github.event.pull_request.head.sha }}
        run: |
          python src/download_model_from_registry.py